import { Section } from "@/app/types";

export const nomenclature: Section = {
  id: "3-nomenclature",
  title: "Nomenclature",
  description: "Nomenclature",
  number: 1,
  type: "section",
  questions: [
    {
      question: "Which ion has the formula NH4+?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "ammonium",
    },
    {
      question: "Which ion has the formula H3O+?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "hydronium",
    },
    {
      question: "Which ion has the formula O2^2-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "peroxide",
    },
    {
      question: "Which ion has the formula OH-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "hydroxide",
    },
    {
      question: "Which ion has the formula CH3COO-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "acetate",
    },
    {
      question: "Which ion has the formula CN-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "cyanide",
    },
    {
      question: "Which ion has the formula N3-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "azide",
    },
    {
      question: "Which ion has the formula CO3^2-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "carbonate",
    },
    {
      question: "Which ion has the formula HCO3-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "bicarbonate",
    },
    {
      question: "Which ion has the formula NO3-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "nitrate",
    },
    {
      question: "Which ion has the formula NO2-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "nitrite",
    },
    {
      question: "Which ion has the formula SO4^2-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "sulfate",
    },
    {
      question: "Which ion has the formula HSO4-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "hydrogen sulfate",
    },
    {
      question: "Which ion has the formula SO3^2-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "sulfite",
    },
    {
      question: "Which ion has the formula HSO3-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "hydrogen sulfite",
    },
    {
      question: "Which ion has the formula PO4^3-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "phosphate",
    },
    {
      question: "Which ion has the formula HPO4^2-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "hydrogen phosphate",
    },
    {
      question: "Which ion has the formula H2PO4-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "dihydrogen phosphate",
    },
    {
      question: "Which ion has the formula ClO4-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "perchlorate",
    },
    {
      question: "Which ion has the formula ClO3-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "chlorate",
    },
    {
      question: "Which ion has the formula ClO2-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "chlorite",
    },
    {
      question: "Which ion has the formula ClO-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "hypochlorite",
    },
    {
      question: "Which ion has the formula CrO4^2-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "chromate",
    },
    {
      question: "Which ion has the formula Cr2O7^2-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "dichromate",
    },
    {
      question: "Which ion has the formula MnO4-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "permanganate",
    },

    {
      question: "Which ion has the formula NH4+?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "ammonium",
    },
    {
      question: "Which ion has the formula H3O+?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "hydronium",
    },
    {
      question: "Which ion has the formula O2^2-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "peroxide",
    },
    {
      question: "Which ion has the formula OH-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "hydroxide",
    },
    {
      question: "Which ion has the formula CH3COO-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "acetate",
    },
    {
      question: "Which ion has the formula CN-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "cyanide",
    },
    {
      question: "Which ion has the formula N3-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "azide",
    },
    {
      question: "Which ion has the formula CO3^2-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "carbonate",
    },
    {
      question: "Which ion has the formula HCO3-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "bicarbonate",
    },
    {
      question: "Which ion has the formula NO3-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "nitrate",
    },
    {
      question: "Which ion has the formula NO2-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "nitrite",
    },
    {
      question: "Which ion has the formula SO4^2-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "sulfate",
    },
    {
      question: "Which ion has the formula HSO4-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "hydrogen sulfate",
    },
    {
      question: "Which ion has the formula SO3^2-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "sulfite",
    },
    {
      question: "Which ion has the formula HSO3-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "hydrogen sulfite",
    },
    {
      question: "Which ion has the formula PO4^3-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "phosphate",
    },
    {
      question: "Which ion has the formula HPO4^2-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "hydrogen phosphate",
    },
    {
      question: "Which ion has the formula H2PO4-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "dihydrogen phosphate",
    },
    {
      question: "Which ion has the formula ClO4-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "perchlorate",
    },
    {
      question: "Which ion has the formula ClO3-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "chlorate",
    },
    {
      question: "Which ion has the formula ClO2-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "chlorite",
    },
    {
      question: "Which ion has the formula ClO-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "hypochlorite",
    },
    {
      question: "Which ion has the formula CrO4^2-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "chromate",
    },
    {
      question: "Which ion has the formula Cr2O7^2-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "dichromate",
    },
    {
      question: "Which ion has the formula MnO4-?",
      options: [
        "ammonium",
        "hydronium",
        "peroxide",
        "hydroxide",
        "acetate",
        "cyanide",
        "azide",
        "carbonate",
        "bicarbonate",
        "nitrate",
        "nitrite",
        "sulfate",
        "hydrogen sulfate",
        "sulfite",
        "hydrogen sulfite",
        "phosphate",
        "hydrogen phosphate",
        "dihydrogen phosphate",
        "perchlorate",
        "chlorate",
        "chlorite",
        "hypochlorite",
        "chromate",
        "dichromate",
        "permanganate",
        "perchlorite",
      ],
      answer: "permanganate",
    },
  ],
};
